function [U,T] = autoGen_cartPoleEnergy(x,q,dx,dq,m1,m2,g,l)
%AUTOGEN_CARTPOLEENERGY
%    [U,T] = AUTOGEN_CARTPOLEENERGY(X,Q,DX,DQ,M1,M2,G,L)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Mar-2022 01:43:33

t2 = cos(q);
U = -g.*l.*m2.*t2;
if nargout > 1
    T = (m2.*((dx+dq.*l.*t2).^2+dq.^2.*l.^2.*sin(q).^2))./2.0+(dx.^2.*m1)./2.0;
end
