function [A,B] = cartPoleJacobian(in1,u,in3)
%CARTPOLEJACOBIAN
%    [A,B] = CARTPOLEJACOBIAN(IN1,U,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    30-Mar-2022 01:02:39

dq = in1(3,:);
g = in3(3,:);
l = in3(4,:);
m1 = in3(1,:);
m2 = in3(2,:);
q = in1(1,:);
t2 = cos(q);
t3 = sin(q);
t4 = dq.^2;
t7 = 1.0./l;
t5 = t2.^2;
t6 = t3.^2;
t8 = m2.*t5;
t9 = -t8;
t10 = m1+m2+t9;
t11 = 1.0./t10;
t12 = t11.^2;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,t11.*(g.*t8-g.*m2.*t6+l.*m2.*t2.*t4)-m2.*t2.*t3.*t12.*(u+g.*m2.*t2.*t3+l.*m2.*t3.*t4).*2.0,-t7.*t11.*(-t3.*u+g.*m1.*t2+g.*m2.*t2+l.*t4.*t8-l.*m2.*t4.*t6)+m2.*t2.*t3.*t7.*t12.*(t2.*u+g.*m1.*t3+g.*m2.*t3+l.*m2.*t2.*t3.*t4).*2.0,1.0,0.0,0.0,0.0,0.0,1.0,dq.*l.*m2.*t3.*t11.*2.0,dq.*m2.*t2.*t3.*t11.*-2.0],[4,4]);
if nargout > 1
    B = [0.0;0.0;t11;-t2.*t7.*t11];
end
